from modules.colors import *
from modules.delete import *
from modules.encoding import *
from modules.ftp import *
from modules.group import *
from modules.help import *
from modules.httpd import *
from modules.ping import *
from modules.workurl import *
from modules.search import *
from modules.first_run_git import *
from modules.mail import *
from modules.license import *